[project]
name = "gateway"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "redis[hiredis]",
    "paho-mqtt",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "cryptography",
    "pydantic-settings",
    "aiomqtt>=2.5.1",
    "shared",
    "pyjwt>=2.13.0",
    "passlib>=1.7.4",
    "bcrypt==4.0.1",
    "httpx>=0.28.1",
]

[tool.uv.sources]
shared = { workspace = true }
