[project]
name = "gateway"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "redis[hiredis]",
    "paho-mqtt",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "cryptography",
    "pydantic-settings",
    "aiomqtt>=2.5.1",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }
