"""Add color field to LogicalZone for UI

Revision ID: 6478b80aac32
Revises: fc2e21fa6575
Create Date: 2026-06-08 13:28:33.274476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6478b80aac32'
down_revision: Union[str, Sequence[str], None] = 'fc2e21fa6575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logical_zones', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logical_zones', 'color')
    # ### end Alembic commands ###
