"""Add spatial fields to LogicalZone for interactive floorplans

Revision ID: 6b47aa6eea5e
Revises: 7fc7f6c1bcb9
Create Date: 2026-06-08 09:57:34.113287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b47aa6eea5e'
down_revision: Union[str, Sequence[str], None] = '7fc7f6c1bcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logical_zones', sa.Column('floor_level', sa.Integer(), nullable=False))
    op.add_column('logical_zones', sa.Column('shape_type', sa.String(length=50), nullable=False))
    op.add_column('logical_zones', sa.Column('width', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('logical_zones', sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('logical_zones', sa.Column('pos_x', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('logical_zones', sa.Column('pos_y', sa.Numeric(precision=6, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logical_zones', 'pos_y')
    op.drop_column('logical_zones', 'pos_x')
    op.drop_column('logical_zones', 'height')
    op.drop_column('logical_zones', 'width')
    op.drop_column('logical_zones', 'shape_type')
    op.drop_column('logical_zones', 'floor_level')
    # ### end Alembic commands ###
