"""Add spatial fields to LogicalZone for interactive floorplans

Revision ID: fc2e21fa6575
Revises: 6b47aa6eea5e
Create Date: 2026-06-08 11:59:00.820476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2e21fa6575'
down_revision: Union[str, Sequence[str], None] = '6b47aa6eea5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_profile', sa.Column('bottom_floor', sa.Integer(), server_default='1', nullable=False))
    op.add_column('home_profile', sa.Column('top_floor', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_profile', 'top_floor')
    op.drop_column('home_profile', 'bottom_floor')
    # ### end Alembic commands ###
